#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Setup monitors / workspaces
if [ "$(xrandr | grep ' connected' | wc -l)" = "2" ]; then
	# Internal + VGA
	xrandr --output DP-1-1 --mode 1280x960 --left-of eDP-1-1 --primary
	bspc monitor DP-1-1 -d I
	bspc monitor eDP-1-1 -d II III IV V VI VII VIII IX X
	
	# VGA only
	# xrandr --output DP-1-1 --mode 1280x960 --primary --output eDP-1-1 --off
	# bspc monitor DP-1-1 -d I II III IV V VI VII VIII IX X
else
	# Internal only
	xrandr --output eDP-1-1 --auto
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Launch programs
# xrdb $HOME/.Xressorces &
picom  --daemon --config $HOME/.config/picom/picom.conf
dunst &
$HOME/.config/polybar/launch.sh &
nitrogen --restore
optimus-manager-qt &
nm-applet &

# Startup sound
mplayer ~/Music/boot.wav &

# Fix for theme issues (optimus-manager-qt has to be already running)
export XDG_CURRENT_DESKTOP=KDE

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
